/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gdwwpxvedoortnjfrgej"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdkd3dweHZlZG9vcnRuamZyZ2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxODEzODcsImV4cCI6MjEwMjc1NzM4N30.oO2s875-M-2FOGFs5Rdtf8bcqfKWJ7z9-83CzLk9T74"
